### ISSUE TITLE
Conflito com Relation reference widget (Master)

### ISSUE THREAD

**Issue by dinizime** [lcoandrade/DsgTools#124]
Erro abaixo apresentado quando selecionando uma camada que possui um campo com Relation Reference widget.

> TypeError: arguments did not match any overloaded call:   QTableWidgetItem(int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'   QTableWidgetItem(QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'   QTableWidgetItem(QIcon, QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'   QTableWidgetItem(QTableWidgetItem): argument 1 has unexpected type 'list' 
Traceback (most recent call last):
  File "C:/Users/diniz/.qgis2/python/plugins\DsgTools\AttributeTools\code_list.py", line 138, in on_comboBox_currentIndexChanged
    self.loadCodeList()
  File "C:/Users/diniz/.qgis2/python/plugins\DsgTools\AttributeTools\code_list.py", line 160, in loadCodeList
    codeItem = QTableWidgetItem(code)
TypeError: arguments did not match any overloaded call:
  QTableWidgetItem(int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'
  QTableWidgetItem(QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'
  QTableWidgetItem(QIcon, QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'
  QTableWidgetItem(QTableWidgetItem): argument 1 has unexpected type 'list'

**Comment by phborba** [comment]
Acho que resolvi agora no commit 40aa583a07f845da852838fbf01ff9ec0608bd3a

Olha lá por favor

**Comment by dinizime** [comment]
Erro resolvido. Porém seria interessante suprimir os campos que são Reference Relation do Code List Viewer ou resolve-los como é feito para Value Relation na Fter.

![image](https://user-images.githubusercontent.com/10109704/29742061-7ac14300-8a4e-11e7-9592-2d65e0fe14e9.png)
