### ISSUE TITLE
Substituir simbolos Dsgtools Military Tools

### ISSUE THREAD

**Issue by dinizime** [lcoandrade/DsgTools#125]
Substituir simbolo _Dsg Tools Militar Tools_ e _Dsg Tools Instaler /Uninstaller_ pelo símbolo do Exército.

**Comment by phborba** [comment]
@dinizime vcs tem o símbolo já no padrão? Se tiver, me passa por email por favor.

**Comment by dinizime** [comment]
Bota o mesmo da que é utilizado na parte do BDGEx (Símbolo do Exército)

**Comment by phborba** [comment]
Feito no commit ef03b1f287d08a7babf38663f5d145abe16990ef
