### ISSUE TITLE
Freezing durante importação de estilo

### ISSUE THREAD

**Issue by rsmaior** [lcoandrade/DsgTools#126]
QGIS 2.18.12
DSGTools 3.0.4

Durante a importação de estilo tenho o seguinte erro seguido de congelamento do QGIS (tenho que dar kill no processo).

> 2017-08-29T15:04:10	1	Traceback (most recent call last):
> 			  File "/home/rodrigo/.qgis2/python/plugins/DsgTools/ServerTools/batchDbManager.py", line 238, in on_importStylesPushButton_clicked
> 			    successList, exceptionDict = self.batchImportStyles(dbsDict, styleDir, selectedStyles, versionList[0])
> 			  File "/home/rodrigo/.qgis2/python/plugins/DsgTools/ServerTools/batchDbManager.py", line 271, in batchImportStyles
> 			    exceptionDict[dbName] =  ':'.join(e.args)
> 			TypeError: sequence item 2: expected string or Unicode, int found

**Comment by rsmaior** [comment]
Mais uma coisa. Fiz isso tanto no servidor local quanto remoto, o resultado foi o mesmo.

**Comment by rsmaior** [comment]
Correção: na verdade não é um freezing propriamente dito, mas o ícone do mouse fica no formato de loading. De qualquer forma, os estilos não estão sendo importados para os bancos.

**Comment by phborba** [comment]
Não consegui reproduzir o problema. Caso persista, favor reabrir o issue.
