### ISSUE TITLE
Erro Ferramenta de reclassificação (3.1 Branch)

### ISSUE THREAD

**Issue by dinizime** [lcoandrade/DsgTools#129]
Erro ao se clicar no botão "Add / Update" quando configurando os botões da ferramenta de reclassificação (Setup).

O erro somente ocorre se utilizar "Assign Shortcut"

> An error has occurred while executing Python code: 
> 
> AttributeError: 'ShortcutChooserWidget' object has no attribute 'getShortcut' 
> Traceback (most recent call last):
>   File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\ProductionTools\FieldToolBox\field_setup.py", line 366, in on_addUpdatePushButton_clicked
>     self.buttonPropDict[fullTableName][self.buttonNameLineEdit.text()] = self.buttonPropWidget.getParameterDict()
>   File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\CustomWidgets\buttonPropWidget.py", line 78, in getParameterDict
>     parameterDict['buttonShortcut'] = self.shortcutWidget.getShortcut()
> AttributeError: 'ShortcutChooserWidget' object has no attribute 'getShortcut'

**Comment by dinizime** [comment]
Outro erro que ocorre é se navegar até o botão na arvore de botões da janela "Reclassification Setup"

> An error has occurred while executing Python code: 
> 
> IndexError: list index out of range 
> Traceback (most recent call last):
>   File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\ProductionTools\FieldToolBox\field_setup.py", line 627, in on_treeWidget_currentItemChanged
>     self.recreateAttributeTable(previous)
>   File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\ProductionTools\FieldToolBox\field_setup.py", line 464, in recreateAttributeTable
>     text = [key for key in self.optionalDict.keys() if  self.optionalDict[key] == attrItem.text(j)][0]
> IndexError: list index out of range

**Comment by phborba** [comment]
Resolvido. Vou fechar e qq coisa abre novo blz?
