### ISSUE TITLE
Help: Migrar help para wiki do github e gerar script para conversão para pdf

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#135]
Atualmente o help do DSGTools encontra-se hospedado no geoportal. Para que ele seja gerado, é feito um documento correspondente ao manual e, em seguida, ele é atualizado manualmente.

A wiki do github permite que, por meio de um script em python, o conteúdo seja convertido para pdf.

Deseja-se que o conteúdo seja gerado uma única vez e que os produtos derivados sejam gerados de maneira automática.

**Comment by phborba** [comment]
Links para ajudar:

https://gist.github.com/rogersachan/40e4f69439b26e1f096f8c91e98b1dee

https://stackoverflow.com/questions/18759738/effortless-export-from-github-wiki

https://gist.github.com/alexeyismirnov/85cdf7b1e9aea4d3494b

https://gist.github.com/romac/1084698

**Comment by phborba** [comment]
Falta trocar os links da wiki

**Comment by jpesperidiao** [comment]
Últimas alterações feitas:

- capa concluída;
- imagens, scripts e PDF migrados para GitHub DSGTools;
- corrigido numeração das imagens (há algumas sem legenda, mas é por não ter pensado em uma mesmo);
- as imagens foram tornadas estáticas, isto é, não alteram a posição no texto; e
- troca dos nomes "Contents" e "Figure" para "Conteúdo" e "Fig.", respectivamente.

Lembrando que o conteúdo está desatualizado. Falta centralizar as imagens dos vídeos de YouTube, que não são numerados por, em princípio, vídeos, não figuras.

**Comment by jpesperidiao** [comment]
Link para versão mais recente já está na Home da Wiki.
