### ISSUE TITLE
Bug na geração de flags na identificação de gaps e overlaps

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#136]
Geometria não adequada na geração de gaps e overlaps. No banco que testei, há mais de uma moldura (pode ser esse o caso que não está sendo tratado).

Talvez tenha que rolar um dissolve das molduras. Várias molduras num mesmo banco é caso de uso, antes que isso seja questionado.

**Comment by phborba** [comment]
<img width="390" alt="captura de tela 2017-09-22 as 20 35 18" src="https://user-images.githubusercontent.com/6131641/30767765-315dfe86-9fd6-11e7-989d-cb25c686286b.png">


exemplo de erro

**Comment by phborba** [comment]
Além disso, mesmo tendo sido rodado snap layer on layer (das camadas de cobertura para a moldura) e topological clean, ainda rodou esse tipo de flag (apaguei as bugadas citadas anteriormente, que permaneceram):

<img width="398" alt="captura de tela 2017-09-22 as 21 01 46" src="https://user-images.githubusercontent.com/6131641/30768091-792b5828-9fd9-11e7-80b8-0518e1df9360.png">

**Comment by phborba** [comment]
Flags também não estão sendo limpas

**Comment by lcoandrade** [comment]
Flags agora estão sendo limpadas antes de rodar de novo. Commit  bdd464e.
No teste que fiz aqui, depois de rodar o Snap layer on layer matou a flag de proximidade com a moldura.

**Comment by phborba** [comment]
Se no banco que eu testei deu essas crecas, algo de errado não está certo :P

**Comment by lcoandrade** [comment]
O seu problema com flags na proximidade da moldura são decorrentes do snap layer on layer. Outra issue foi aberto pra esse problema.

O problema de haver mais de uma moldura foi resolvido com o uso de ST_Union nas molduras no commit  06a6047. Testa por favor.

**Comment by phborba** [comment]
testei e resolveu
