### ISSUE TITLE
Bug na ferramenta de seleção: Ferramenta não funciona com múltiplos sistemas de referência

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#141]
Ao utilizar múltiplos src, a ferramenta só funciona para alguns

**Comment by lcoandrade** [comment]
Isso deve ser problema ao pegar as coordenadas do canvas. Isso acontecia na ferramenta de gabarito também.

**Comment by lcoandrade** [comment]
Isso acontece quando seleciona por ponto, retângulo ou os dois?

**Comment by phborba** [comment]
Por ponto. No retângulo funciona =/
![image](https://user-images.githubusercontent.com/6131641/30996203-64efb334-a495-11e7-83e8-e67d54236b7a.png)

**Comment by lcoandrade** [comment]
Resolvido no commit 1290703.
