### ISSUE TITLE
Nova funcionalidade: Processo para identificação de pontas soltas

### ISSUE THREAD

**Issue by lcoandrade** [lcoandrade/DsgTools#142]
O processo deve ser capaz de identificar pontas soltas em camadas vetoriais do tipo linha. As flags deverão registrar a ponta solta (ponto), o id da feição e a camada da feição.

**Comment by lcoandrade** [comment]
Processo feito no commit  8f982be

**Comment by phborba** [comment]
Testei aqui e me parece tudo ok. Talvez seja o caso dar a opção de usar a moldura como filtro para diminuir a quantidade de falsos positivos.

**Comment by phborba** [comment]
Duplicado do issue #97 
Vou fechar esse e abri um de melhoria (para colocar o filtro de falsos positivos)
