### ISSUE TITLE
plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [lcoandrade/DsgTools#146]
# Problem
I see they are a lot of bugs that are listed here. Can you please sort these out before I approve the plugin

# Solution
Fix the bugs

**Comment by phborba** [comment]
Hoje Mazano, how are you doing?

We use github issues to track our activities. Only issues tagged with Bug are indeed bugs. All the other issues are enhancements that our users have asked us. We use the project functionality of github to assign tasks.

There are only 3 bugs in our current release candidate (3.0.7) and we have only released a new one from 3.0.6 to fix some bugs that came up yesterday while we were teaching some people to use DSGTools.

Please consider all the information above to approve our plugin. 

Kind regards, 
Philipe

**Comment by NyakudyaA** [comment]
I have approved the plugin

**Comment by phborba** [comment]
Thank you man! Please feel free to suggest improvements to our plugins!
