### ISSUE TITLE
Processo de Identificação de Gaps

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#153]
Da mesma forma que foi feito um processo de identificação de overlaps ignorando a moldura, seria interessante ter um de identificação de gaps. 

Gaps não são somente aqueles com a moldura, pode haver gap entre feições, exemplo um trecho de massa dagua e uma floresta adjacentes.

Sugestão de procedimento: calcular o convex hull de todas as feições e fazer a diferença dele com o union de todas as feições.

**Comment by lcoandrade** [comment]
Essa abordagem não dá certo, é fácil achar geometrias isoladas em que o convex hull menos ela mesma gera diferenças... Tem que ter mais condicionantes. Então, para não reinventar a roda, eu usei o Postgis-addons com o ST_GeoTableSummary pegando o sumário 4 (S4).

**Comment by lcoandrade** [comment]
Podem testar para verificar se acham algo errado @dinizime, @phborba e @jpesperidiao?
