### ISSUE TITLE
Melhoria: Atualizar o método updateOriginalLayer para trabalhar com o OverlayElementsWithAreasProcess

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#154]
O método updateOriginalLayer precisa ser adaptado para o uso com o processo OverLayElementsWithAreas.

Casos de uso a serem atendidos:
- [x] Alterar somente feições processadas;
- [x] Apagar feições fora da lista;

**Comment by phborba** [comment]
Implementado o updateOriginalLayerV2. Ainda não está 100%, estou testando processo a processo.

**Comment by phborba** [comment]
Fiz testes de performance e o tempo caiu cerca de 75% nos testes que eu fiz no clean nas camadas VEG_D e Trecho_Drenagem_L (4 cartas 25k juntas), aproximadamente 10600 elementos no total.
@lcoandrade e @dinizime vcs podem dar uma testada? Eu vou migrar todos os processos para o V2 e qq coisa voltamos atrás para o original, blz?

**Comment by lcoandrade** [comment]
Nos testes que fiz com o clean houve uma redução de 50 a 56%. Até o momento não vi problemas... Só a mudança do request do original layer para usar o NoGeometry já não seria suficiente?

**Comment by phborba** [comment]
Não, a melhoria foi também minimizar as chamadas do getFeatures e a forma diferente de atualizar geometria. A primeira melhoria vi no link do comentário do código e a segunda vi na api (pedem pra usar esse pelo id ao invés de updateFeature)

**Comment by phborba** [comment]
Cada chamada do getFeatures abre conexão com o banco e é mais custoso que chamar uma vez e montar o dicionário.

**Comment by phborba** [comment]
Observação:o parâmetro tipo de input do v.overlay é o índice da interface do processing, sendo 0 para área e 1 para linha.

**Comment by dinizime** [comment]
Realizei alguns testes, melhoras significativas. Amanhã farei a pré validação de algumas cartas.

Essas optimizações já consideram agrupar os edit commands?

**Comment by phborba** [comment]
Sim, já está com o agrupamento de edit, tanto que com um control+z desfaz o que o processo todo fez.
