### ISSUE TITLE
Ferramenta Remove Duplicate Elements cria flags de elementos duplicados incorretamente

### ISSUE THREAD

**Issue by dinizime** [lcoandrade/DsgTools#160]
### Subject of the issue (Assunto do problema)
Ao utilizar a ferramenta de validação Remove Duplicate Elements são criados flags do processo Identify Duplicate Geometries incorretamente.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 10
* version of QGIS (Versão do QGIS):  2.18.13
* version of DSGTools (Versão do DSGTools): 3.1_dev

**Comment by phborba** [comment]
@dinizime quando roda o processo, falta geração de duplicata ou foi gerado falso-positivo? Não entendi como replicar

**Comment by dinizime** [comment]
Basta aplicar a ferramenta Remove Duplicate Elements em um dataset que tenha elementos duplicados. Ele irá corrigir os erros sem nenhum problema, porém ele também criará os flags desnecessariamente.

**Comment by phborba** [comment]
Ahh acho que entendi, no caso de já ter sido rodado o processo, não rodar a identificação original, é isso?

**Comment by phborba** [comment]
Acho que resolvi no commit 3680d2964f27eed85a37fa7f2c8499436c5abd1c

@dinizime testa pra mim ae e me diz se é isso mesmo, por favor.
