### ISSUE TITLE
Proposta de ferramentas do Clean

### ISSUE THREAD

**Issue by lcoandrade** [lcoandrade/DsgTools#161]
Segundo a documentação do v.clean o rmsa deve ser seguido de break e rmdupl. Sendo assim, proponho testes para verificar se a mudança de:
tools = 'break,rmsa,rmdangle'
para
tools = 'rmsa,break,rmdupl,rmdangle'

Afeta o funcionamento do clean positiva ou negativamente.
Caso o efeito seja positivo, a mudança a troca deve ser feita também no topological clean.

@phborba e @dinizime, podem testar? Pelo que vi aqui em casa, a mudança não afetou. Quero saber se nos casos que ocorrem sumiço de feições a troca resolve o problema.

**Comment by phborba** [comment]
Segunda testo

**Comment by dinizime** [comment]
Nenhuma mudança aparente.
