### ISSUE TITLE
Importação de estilo gerando erros

### ISSUE THREAD

**Issue by rsmaior** [lcoandrade/DsgTools#166]
Kubuntu Linux 16.04.3 (64 bits)
QGIS 2.18.13
DSGTools 3.0.8

A importação de estilo tá gerando o seguinte erro:
```
An error has occurred while executing Python code: 

TypeError: sequence item 2: expected string or Unicode, int found 
Traceback (most recent call last):
  File "/home/rodrigo/.qgis2/python/plugins/DsgTools/ServerTools/batchDbManager.py", line 238, in on_importStylesPushButton_clicked
    successList, exceptionDict = self.batchImportStyles(dbsDict, styleDir, selectedStyles, versionList[0])
  File "/home/rodrigo/.qgis2/python/plugins/DsgTools/ServerTools/batchDbManager.py", line 271, in batchImportStyles
    exceptionDict[dbName] =  ':'.join(e.args)
TypeError: sequence item 2: expected string or Unicode, int found


Python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] 
QGIS version: 2.18.13 Las Palmas, 8cba0bb 

Python Path:
/usr/share/qgis/python/plugins/processing
/home/rodrigo/.qgis2/python/plugins/postgis_geoprocessing
/usr/share/qgis/python
/home/rodrigo/.qgis2/python
/home/rodrigo/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2
/home/rodrigo/.qgis2//python
/home/rodrigo/.qgis2/python/plugins/mmqgis/forms
/home/rodrigo/.qgis2/python/plugins/DsgTools
/home/rodrigo/.qgis2/python/plugins/DsgTools/ProductionTools/CopyPasteTool
/home/rodrigo/.qgis2/python/plugins/DigitizingTools/tools

```
Além disso, após a importação do estilo,  o ícone do mouse fica indefinidamente no formato de loading. Os cliques etc funcionam normalmente, porém sempre com o ícone de loading. A única forma de eliminar isso é fechando e reabrindo o QGIS. Seguem as imagens ilustrativas do ícone comum e do ícone de loading.
![icone_comum](https://user-images.githubusercontent.com/11916280/33073685-ce5a7b76-ceaa-11e7-8ec7-671527aa1f72.png)
![loading_eterno](https://user-images.githubusercontent.com/11916280/33073686-ce866c72-ceaa-11e7-8ed2-457616729a8f.png)

**Comment by rsmaior** [comment]
Segue a pasta dos estilos zipada
[2_CGEO.zip](https://github.com/lcoandrade/DsgTools/files/1491461/2_CGEO.zip)

**Comment by rsmaior** [comment]
Troquei o nome da pasta de 2_CGEO para 2CGEO, porém o problema persiste.

**Comment by lcoandrade** [comment]
Testou no 3.1_dev? Usei a pasta aqui e funcionou perfeitamente...

**Comment by phborba** [comment]
@rsmaior ainda tem erro?

**Comment by rsmaior** [comment]
Acabei de baixar o 3.1_dev e testar. O bug permanece aqui.

**Comment by rsmaior** [comment]
Havia um arquivo com acento (tra_trecho_rodoviário.qml), sendo necessárias melhoras de error handling no arquivo batchDbManager.py

código 273:
`                        if isinstance(arg, int):
                            s = str(arg)
                        else:
                            s = '{}'.format(arg.encode('utf-8'))`

código 152
`                QgsMessageLog.logMessage(self.tr('Error for database ')+ errorDb + ': ' +exceptionDict[errorDb].decode('utf-8'), "DSG Tools Plugin", QgsMessageLog.CRITICAL)
`

**Comment by lcoandrade** [comment]
Fiz uns ajustes na mensagem de erro. No computador do Souto Maior aparece agora aparece a mensagem indicando o problema corretamente (commit 5e849b6). A questão e verificar o motivo de no meu computador, tanto no trabalho (Linux) quanto em casa (macOS), não dar problema apesar de haver um arquivo com acento no nome.

**Comment by phborba** [comment]
@lcoandrade sobe o ranger verde ae! hahaha

**Comment by lcoandrade** [comment]
Agora é feita uma verificação nos nomes dos arquivos antes de tentar importar. Esta verificação checa se o arquivo é oculto (iniciando com .) e checa se há caracteres especiais por meio de uma expressão regular. Feito no commit 280856d.
