### ISSUE TITLE
Erro na exportação de perfis permissões 

### ISSUE THREAD

**Issue by lcoandrade** [lcoandrade/DsgTools#168]
### Subject of the issue (Assunto do problema)
Problema ao tentar exportar perfis de permissões

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): macOS High Sierra
* version of QGIS (Versão do QGIS): 2.18.9
* version of DSGTools (Versão do DSGTools): 3.1_dev 

### Steps to reproduce (Passos para reproduzir)
Selecionar um perfil e clicar em exportar

### Expected behaviour (Comportamento esperado)
Exportar corretamente o perfil permitindo ao usuário selecionar o local de destino

### Actual behaviour (Comportamento atual)
Exceção com mensagem de erro

**Comment by phborba** [comment]
Resolvido no commit 9e4a09d38db521585584c48911fe0fd3bc95d259

**Comment by phborba** [comment]
@lcoandrade testa pra mim por favor?

**Comment by lcoandrade** [comment]
Problema resolvido!
