### ISSUE TITLE
Renomear "Identify Overlaps", "Identify Gaps" e "Identify Gaps and Overlaps"

### ISSUE THREAD

**Issue by rsmaior** [lcoandrade/DsgTools#175]
### Subject of the issue (Assunto do problema)
Renomear os processos de validação  "Identify Overlaps", "Identify Gaps" e "Identify Gaps and Overlaps" para melhor refletir seus respectivos domínios de atuação, incluindo algo como 'intraclasses' e 'interclasses' nos nomes dos processos.

### Your environment (Seu ambiente)
Kubuntu Linux 16.04.3 (64 bits)
QGIS 2.18.13
DSGTools 3.1

### Steps to reproduce (Passos para reproduzir)
Abrir a ferramenta de validação e olhar a lista de processos de validação.

### Expected behaviour (Comportamento esperado)
A lista de processos conter os seguintes itens:
"Identify Overlaps (Intraclasses)"
"Identify Gaps (Intraclasses)" 
"Identify Gaps and Overlaps (Intraclasses and interclasses)"

### Actual behaviour (Comportamento atual)
Os processos se chamam:
"Identify Overlaps"
"Identify Gaps" 
"Identify Gaps and Overlaps"

**Comment by phborba** [comment]
Processos renomeados no commit 44646d63a04f029f5f48beaad226a509394da2cc
Novos nomes:
Identify Layer Overlaps
Identify Layer Gaps
Identify Coverage Gaps and Overlaps

@rsmaior os novos nomes atendem?

**Comment by rsmaior** [comment]
Perfeitamente.

**Comment by rsmaior** [comment]
Sim. MAs uma melhoria:
Identify Coverage Gaps and Overlaps →  Identify Earth Coverage Gaps and Overlaps
