### ISSUE TITLE
Help do "Colar na grade"

### ISSUE THREAD

**Issue by rsmaior** [lcoandrade/DsgTools#36]
Última frase tá errada ou incompleta.

> Este processo funciona com o uso da função ST_SnapToGrid do PostGIS. O objetivo desta ferramenta é ajustar a precisão das coordenadas. Ele é essencial para que os processamentos topológicos corretamente, para garantir que, por exemplo, duas geometrias se toquem de fato.

**Comment by rsmaior** [comment]
Outra coisa, na documentação oficial diz que a função ST_SnapToGrid "Snap all points of the input geometry to a regular grid", seria o caso adicionar na documentação algo como "Este processo funciona com o uso da função ST_SnapToGrid do PostGIS, que cola todos os pontos da geometria num grid regular." Fica bem mais claro com essa explicação entender o que está acontendo.

**Comment by rsmaior** [comment]
Mais duas coisas no seguinte trecho:

> Resumindo, esse processo deve ser rodado para, por exemplo, transformas uma coordenada com 17 casas decimais para uma coordenada com apenas 3 casa decimais (ficando limitada aos milímetros, o que é suficiente).

1) O comportamento padrão é um grid com coordenadas de três casas decimais de precisão?
2) transformas → transformar

**Comment by rsmaior** [comment]
Outro trecho com erro tipográfico:

> Os paâmetros desse processo são os presentes na figura abaixo.

**Comment by lcoandrade** [comment]
Sugestões aceitas!
