### ISSUE TITLE
Help da Criação de bancos de dados em lote 

### ISSUE THREAD

**Issue by rsmaior** [lcoandrade/DsgTools#39]
Falta acrescentar que neste modo de criação de bancos de dados as molduras tambám são criadas junto.

Sugestão:

> Visando os grandes produtores de geoinformação o DSGTools permite agora a criação de bancos de dados em lote, como se pode ver na figura abaixo, facilitando a criação de bancos para grandes projetos. Neste modo, as molduras de cada banco de dados também são criadas.

**Comment by lcoandrade** [comment]
Comentários sobre criação de molduras feito.
