### ISSUE TITLE
Compact Help Images

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#40]
Só a pasta de imagens do help está passando de 13Mb, o limite do plugin são 15Mb

**Comment by phborba** [comment]
Só a pasta de imagens do help está passando de 13Mb, o limite do plugin são 15Mb

**Comment by lcoandrade** [comment]
As imagens já estão compactadas.

**Comment by phborba** [comment]
Então vamos remover esse bagulho do dsgtools! Tá muito grande! HAHAHAHAHAHAHA

**Comment by lcoandrade** [comment]
Fechando essa bodega!!!! Já está no seu github!!! Para de perturbar... rs
