### ISSUE TITLE
ferramentas V.clean 

### ISSUE THREAD

**Issue by CarlosCagna** [lcoandrade/DsgTools#46]
Olá, vi a palestra de vocês na mundoGEO,  sou do IBGE, e achei as ferramentas bem interessantes, desenvolvi uma ferramenta parecida com o que vocês estão fazendo para reparar as geometrias  com o V.clean, coloquei o plugin la no repositório do qgis, ta como Repair Geometry, a vezes pode ser útil para vocês.

**Comment by CarlosCagna** [comment]
a desculpa ter mandando mensagem por aqui, mas não encontrei outro lugar no github, comecei a usar agora

**Comment by phborba** [comment]
Boa tarde Carlos!

Excelente notícia! Com certeza vamos dar uma olhada no que vocês fizeram. Caso vocês tenham interesse em trabalhar juntos, é só dar um toque que podemos fazer algo juntos.

Um abraço!

Philipe Borba
