### ISSUE TITLE
Melhoramentos na Ferramenta de Reclassificação

### ISSUE THREAD

**Issue by LEOXINGU** [lcoandrade/DsgTools#48]
- Necessidade de que o formulário apareça após a reclassificação de cada feição para que atributos (por exemplo "nome") sejam preenchidos individualmente.
- Não permitir que feições desapareçam devido à reclassificação errada (entre classes de geometrias diferentes).
- Fixar o painel da ferramenta de reclassificação ao projeto do QGIS sem a necessidade de abrir e configurar a ferramenta todas as vezes que for utilizá-la.

**Comment by phborba** [comment]
Itens 1 e 2 implementados. Item 3 não será implementado no momento (o dsgtools era assim, porém teve que mudar para o modelo atual)
