### ISSUE TITLE
Ferramenta de (Re)classificação: verificar tipo de geometria ao reclassificar e rejeitar tipos diferentes

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#53]
Possibilidade de impedir situações como reclassificar ponto para área, linha para ponto e etc.

**Comment by phborba** [comment]
Resolvido no commit f81ab2f8ba757a3996662c4f25f67e17fa26e3e7

@lcoandrade confere ae por favor

**Comment by phborba** [comment]
@LEOXINGU o sr pode conferir por favor?

**Comment by LEOXINGU** [comment]
Está funcionando parcialmente, mas quando selecionamos duas feições de primitivas diferentes (por exemplo um ponto e uma linha) e tentamos reclassificá-las, a ferramenta não reclassifica e some com uma das feições. Ou seja, ainda continua permitindo que as feições "desapareçam" quando o operador faz algo errado.
Deveria ter um mecanismo de alerta, por exemplo: "Selecione feições somente com a mesma geometria!" Sem permitir que o operador faça o procedimento errado.

**Comment by phborba** [comment]
Ok, vou resolver isso, valeu pelo feedback!

**Comment by phborba** [comment]
Acho que agora resolvi no commit 51a531e092b790fd4e30d3941ab735bf06f0709e

@LEOXINGU o sr pode conferir por gentileza?

**Comment by LEOXINGU** [comment]
Agora está 100%.
Os reambuladores do 3º CGEO agradecem.

**Comment by lcoandrade** [comment]
Beleza, vou fechar o ticket devido ao feedback do @LEOXINGU .
