### ISSUE TITLE
Ferramenta de seleção genérica: Seleção de feições sobrepostas

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#69]
No QGIS, ao se utilizar a ferramenta de identificação no modo seleção de camadas, quando há camadas sobrepostas, é aberto um context menu com o nome das camadas as quais as feições pertencem e, em seguida, quando o usuário escolhe qual camada ele deseja, o formulário de feições aparece. Deseja-se replicar esse comportamento, porém ao invés de abrir a tabela de atributo, deseja-se que a feição escolhida seja selecionada.

**Comment by dinizime** [comment]
Esse comportamento é mais util se considerar somente geometrias da mesma classe, seguindo a prioridade ponto > linha > área.

Por exemplo, um ponto sobre um polígono não é desejável que apareça o menu de contexto (que requer um clique adicional), ele deveria selecionar diretamente o ponto. Se o usuario quiser selecionar o poligono ele pode clicar em um local que o objeto não tem sobreposição.

No caso de dois polígonos sobrepostos por exemplo é o caso ter o menu de contexto.

**Comment by phborba** [comment]
Além disso, quando o context menu for aberto, ao selecionar determinada linha, um rubberband deve ser criado iluminando a feição a ser selecionada.

**Comment by jpesperidiao** [comment]
Concordo com a hierarquização das geometrias. Tenho um porém, mais para uma dúvida: a _bounding box_ do mouse não está muito grande pra uma determinada resolução de trabalho? Por exemplo, às vezes quer-se selecionar de fato um polígono, mas pela _bounding box_ do mouse incluir um ponto, se a hierarquia for rígida, o polígono será ignorado; isso não forçaria o usuário a ficar mexendo demais no _zoom_ de trabalho?

**Comment by phborba** [comment]
Em progresso no branch 3.1_dev_GenericSelectionTool

**Comment by jpesperidiao** [comment]
Pessoal, terminei aqui. Fiz uns testes e, a princípio, está funcionando.

**Comment by jpesperidiao** [comment]
Commit #[7224a1b](https://github.com/lcoandrade/DsgTools/commit/7224a1b9f7ec5d3af4fdbed34c13ff230b23cb0d)

**Comment by phborba** [comment]
Vou verificar agora de noite

**Comment by phborba** [comment]
@jpesperidiao está show de bola, até agora não achei erros. Gostaria que você adicionasse o caso de quando muda a linha da seleção genérica, cria um rubberband com a geometria a ser selecionada, mostrando dessa forma a geometria que está para ser selecionada.

**Comment by phborba** [comment]
Minto, achei erro aqui:

`Traceback (most recent call last):
  File "/Users/philipeborba/.qgis2/python/plugins/DsgTools/ProductionTools/CopyPasteTool/multiLayerSelect.py", line 285, in createContextMenu
    layerList = self.getPrimitiveDict(e, hasControlModifyer = selected)
  File "/Users/philipeborba/.qgis2/python/plugins/DsgTools/ProductionTools/CopyPasteTool/multiLayerSelect.py", line 176, in getPrimitiveDict
    if (not hasControlModifyer and e.button() == QtCore.Qt.LeftButton) or (hasControlModifyer and e.button() == QtCore.Qt.RightButton):
AttributeError: 'QPoint' object has no attribute 'button'
`
aconteceu quando cliquei com botão esquerdo depois com o direito. Os outros comportamentos não estão funcionando direito:

- o control+clique direito deveria limpar a seleção
- botão direito deveria abrir a tabela de atributos

**Comment by phborba** [comment]
Esquece a iluminada @jpesperidiao, não tem sinal pra pegar quando troca de item no menu. Só corrige os bugs por favor

**Comment by phborba** [comment]
@jpesperidiao 
http://pyqt.sourceforge.net/Docs/PyQt4/qaction.html

sinal hovered faz o que queremos

olha também https://github.com/qgis/QGIS/blob/master/src/gui/qgsidentifymenu.cpp que é a implementação do menu de identificar (que cria o rubberband que eu quero)

**Comment by jpesperidiao** [comment]
Alterei lá! commit [57c4c1a](https://github.com/lcoandrade/DsgTools/commit/57c4c1a9123551d8916c7f3bee8a1f1b6f9ee815)

**Comment by phborba** [comment]
`
An error has occurred while executing Python code: 

AttributeError: 'QPoint' object has no attribute 'button' 
Traceback (most recent call last):
  File "/Users/philipeborba/.qgis2/python/plugins/DsgTools/ProductionTools/CopyPasteTool/multiLayerSelect.py", line 284, in createContextMenu
    layerList = self.getPrimitiveDict(e, hasControlModifyer = selected)
  File "/Users/philipeborba/.qgis2/python/plugins/DsgTools/ProductionTools/CopyPasteTool/multiLayerSelect.py", line 176, in getPrimitiveDict
    if (not hasControlModifyer and e.button() == QtCore.Qt.LeftButton) or (hasControlModifyer and e.button() == QtCore.Qt.RightButton):
AttributeError: 'QPoint' object has no attribute 'button'
`

ocorre quando dá control+clique direito e há uma seleção já feita

**Comment by jpesperidiao** [comment]
Não tô conseguindo reproduzir esse... Aqui funciona. Vou pedir pra testarem em outro computador.

**Comment by jpesperidiao** [comment]
@phborba Cara, achei uma parada estranha. Vê se o que tu tem é o do último commit do Branch 3.1_dev_GenericSelctionTool e tenta fazer os testes com o debbuger desligado (tu tava com ele ligado, né?).

**Comment by phborba** [comment]
Tava não, tô testando como se usuário fosse. Deu esse erro agora:
`
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'QApplication' 
Traceback (most recent call last):
  File "/Users/philipeborba/.qgis2/python/plugins/DsgTools/ProductionTools/CopyPasteTool/multiLayerSelect.py", line 282, in createContextMenu
    try:
AttributeError: 'NoneType' object has no attribute 'QApplication'

`

**Comment by phborba** [comment]
Para reproduzir: 

1. Selecionar uma feição usando a seleção via combo;
2. Segurar control e clicar com o botão direito.

**Comment by phborba** [comment]
testei de novo aqui com o commit f18682e4e2b9618500db3232110b767e0b10180c e deu certo

**Comment by phborba** [comment]
@jpesperidiao faz o merge no 3.1_dev por favor

**Comment by phborba** [comment]
Merge feito no branch 3.1_dev
