### ISSUE TITLE
Caixa de Ferramentas de Validação (interface): Botão para limpar flags (por processo ou todas)

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#70]
Atualmente, somente ao rodar novamente um processo que gera determinado tipo de flags que são apagadas as flags. Deseja-se um botão para limpar determinado tipo de flag ou todas.

**Comment by phborba** [comment]
@dinizime dá uma mão ae por favor. O @jpesperidiao está fazendo esse ticket e temos alguns questionamentos.

Pendências/Ideias a serem discutidas:
- Alterar filtro das flags (usar o atual ou algum novo? Casos de uso pensados: filtrar por processo e por classe; filtros não excludentes);
- Iterador de feições dentro do visualizador / Utilizar iterador do dsgtools;
- Apagar ou marcar como visitadas (qual é a diferença?)

**Comment by dinizime** [comment]
Eu acredito que os flags devem ser tratados como uma camada comum e carregados para o usuário manipula-los conforme o interesse (na prática hoje eu trabalho assim).
Eu utilizo o inspetor de feições para navegar nos flags.

Apagar as feições enquanto está iterando normalmente confunde o iterador de feições, assim eu prefiro não apagar, e só apagar no fim do processo (que eu faço abrindo a tabela de atributos do aux_validacao e apagando utilizando a interface do qgis).

**Comment by lcoandrade** [comment]
Erro encontrado usar o menu de contexto Remove Flags:
File "/Users/luiz/.qgis2/python/plugins/DsgTools/ValidationTools/validation_toolbox.py", line 94, in removeCurrentFlag
    flagId = self.tableView.selectionModel().selection().indexes().data()
AttributeError: 'list' object has no attribute 'data'

**Comment by lcoandrade** [comment]
Erro ao mudar o item do combobox para Class Name:
File "/Users/luiz/.qgis2/python/plugins/DsgTools/ValidationTools/validation_toolbox.py", line 328, in refreshOnChangeProcessOrClass
    listProcessesOrClasses = self.configWindow.widget.abstractDb.fillComboBoxProcessOrClasses(filterType)
  File "/Users/luiz/.qgis2/python/plugins/DsgTools/Factories/DbFactory/postgisDb.py", line 3461, in fillComboBoxProcessOrClasses
    raise Exception(self.tr("Problem filtering flags: ")+query.lastError().text())
Exception: Problem filtering flags:

**Comment by lcoandrade** [comment]
Após Clicar no Botão Clear All Flags ocorre erro de filtragem de flags.

**Comment by jpesperidiao** [comment]
Isso aí tá com cara de quando eu tentei colocar o _context menu_ aceitando _multiselection_. Qual o branch que tá usando?

**Comment by lcoandrade** [comment]
3.1_dev

**Comment by jpesperidiao** [comment]
Vou olhar o código aqui.

**Comment by jpesperidiao** [comment]
Commitei umas mudanças. Testei e, aparentemente resolveu. Seria bom definir melhorar o fix do Enum que eu fiz depois.

**Comment by jpesperidiao** [comment]
Acho que agora foi, testei alguns casos aqui e não percebi erros. Troquei o nome do botão de "Clear _Selected_ Flags" para "Clear _Filtered_ Flags", acho que representa melhor o comportamento do botão.
