### ISSUE TITLE
Caixa de Ferramentas de Validação (interface): Repetir último processo rodado

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#80]
Deseja-se um botão com a possibilidade de repetir o último processo rodado, com os mesmos parâmetros entrados.

**Comment by phborba** [comment]
Implementação terminada no commit 79a6a4e2c3fef6eb74fed43710db601597efb055

**Comment by phborba** [comment]
@dinizime e @lcoandrade vcs podem olhar?

**Comment by lcoandrade** [comment]
Em telas menores, tipo 13 polegadas, a largura do dock de validação está ocupando boa parte da tela. Sugiro mudar a disposição dos botões na parte inferior, para que não haja 3 botões em uma mesma linha no layout.
