### ISSUE TITLE
Nova Funcionalidade: Processo de validação para identificação de buracos (gaps) e sobreposições (overlaps) na Cobertura Terrestre

### ISSUE THREAD

**Issue by phborba** [lcoandrade/DsgTools#96]
Durante o processo de aquisição, é necessário verificar se não há inconsistências na cobertura terrestre, ou seja, se não há buracos (gaps) ou sobreposições (overlaps). Neste processo espera-se que o processo seja executado e os erros detectados sejam exibidos no formato de flags.

**Comment by phborba** [comment]
Podia ter rodar somente com o selecionado nesse processo

**Comment by phborba** [comment]
Bugs relacionados: issue #136

**Comment by phborba** [comment]
Para fechar esse issue, basta reverter o submodule e colocar os códigos do postgis-addons no github conforme issue #139

**Comment by lcoandrade** [comment]
Fechado por meio do commit 8c0abb8.
